name: Release JAR

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn package

      - name: Release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Find only the thread-ordering-benchmarks.jar file
            const targetDir = path.join(process.env.GITHUB_WORKSPACE, 'target');
            const jarFile = path.join(targetDir, 'thread-ordering-benchmarks.jar');
            
            // Create release
            const tagName = process.env.GITHUB_REF.replace('refs/tags/', '');
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              name: `Release ${tagName}`,
              generate_release_notes: true
            });
            
            // Upload only the specific jar file
            if (fs.existsSync(jarFile)) {
              await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.data.id,
                name: 'thread-ordering-benchmarks.jar',
                data: fs.readFileSync(jarFile)
              });
            } else {
              core.setFailed("Could not find thread-ordering-benchmarks.jar in the target directory");
            }